"use strict";

// DATA COLUMN MAPPING
module.exports.API_DATAMAP = 'API_DATAMAP';
module.exports.ADD_BASE = 'ADD_BASE';
module.exports.ADD_GROUP = 'ADD_GROUP';
module.exports.ADD_SERIES = 'ADD_SERIES';
module.exports.ADD_IGNORE = 'ADD_IGNORE';
module.exports.ADD_ANNOTATIONS = 'ADD_ANNOTATIONS';

module.exports.REMOVE_BASE = 'REMOVE_BASE';
module.exports.REMOVE_GROUP = 'REMOVE_GROUP';
module.exports.REMOVE_SERIES = 'REMOVE_SERIES';
module.exports.REMOVE_IGNORE = 'REMOVE_IGNORE';
module.exports.REMOVE_ANNOTATIONS = 'REMOVE_ANNOTATIONS';

module.exports.RESET_DATAMAP = 'RESET_DATAMAP';

// ATTACH DATA
module.exports.API_DATA = 'API_DATA';
module.exports.ATTACH_DATA = 'ATTACH_DATA';

// AXES
module.exports.API_AXES = 'API_AXES';

// COLOR AXIS
module.exports.SET_COLOR_SCHEME = 'SET_COLOR_SCHEME';
module.exports.SET_COLOR = 'SET_COLOR';
module.exports.UNSET_COLOR = 'UNSET_COLOR';
module.exports.RESET_COLOR = 'RESET_COLOR';
module.exports.SET_QUANTIZE = 'SET_QUANTIZE';
module.exports.UNSET_QUANTIZE = 'UNSET_QUANTIZE';
module.exports.SET_QUANTIZE_COLUMN = 'SET_QUANTIZE_COLUMN';
module.exports.UNSET_QUANTIZE_COLUMN = 'UNSET_QUANTIZE_COLUMN';
module.exports.SET_QUANTIZE_DOMAIN = 'SET_QUANTIZE_DOMAIN';
module.exports.SET_QUANTIZE_RANGE = 'SET_QUANTIZE_RANGE';

// BASE AXIS
module.exports.SET_BASE_TYPE = 'SET_BASE_TYPE';
module.exports.SET_DATE_FORMAT = 'SET_DATE_FORMAT';
module.exports.UNSET_DATE_FORMAT = 'UNSET_DATE_FORMAT';
module.exports.SET_BASE_SINGLE_DATESTRING = 'SET_BASE_SINGLE_DATESTRING';
module.exports.SET_BASE_SINGLE_FREQUENCY = 'SET_BASE_SINGLE_FREQUENCY';
module.exports.SET_BASE_DOUBLE_DATESTRING = 'SET_BASE_DOUBLE_DATESTRING';
module.exports.SET_BASE_DOUBLE_FREQUENCY = 'SET_BASE_DOUBLE_FREQUENCY';
module.exports.SET_BASE_SINGLE_TICKS = 'SET_BASE_SINGLE_TICKS';
module.exports.SET_BASE_SINGLE_CUSTOMTICKS = 'SET_BASE_SINGLE_CUSTOMTICKS';
module.exports.SET_BASE_DOUBLE_TICKS = 'SET_BASE_DOUBLE_TICKS';
module.exports.SET_BASE_DOUBLE_CUSTOMTICKS = 'SET_BASE_DOUBLE_CUSTOMTICKS';
module.exports.SET_BASE_MIN = 'SET_BASE_MIN';
module.exports.SET_BASE_MAX = 'SET_BASE_MAX';
module.exports.SET_BASE_LABEL = 'SET_BASE_LABEL';
module.exports.SET_BASE_SUFFIX = 'SET_BASE_SUFFIX';
module.exports.SET_BASE_PREFIX = 'SET_BASE_PREFIX';

// VALUE AXIS
module.exports.SET_VALUE_SINGLE_TICKS = 'SET_VALUE_SINGLE_TICKS';
module.exports.SET_VALUE_SINGLE_CUSTOMTICKS = 'SET_VALUE_SINGLE_CUSTOMTICKS';
module.exports.SET_VALUE_DOUBLE_TICKS = 'SET_VALUE_DOUBLE_TICKS';
module.exports.SET_VALUE_DOUBLE_CUSTOMTICKS = 'SET_VALUE_DOUBLE_CUSTOMTICKS';
module.exports.SET_VALUE_MIN = 'SET_VALUE_MIN';
module.exports.SET_VALUE_MAX = 'SET_VALUE_MAX';
module.exports.SET_VALUE_LABEL = 'SET_VALUE_LABEL';
module.exports.SET_VALUE_SUFFIX = 'SET_VALUE_SUFFIX';
module.exports.SET_VALUE_PREFIX = 'SET_VALUE_PREFIX';

// MARGINS
module.exports.API_MARGINS = 'API_MARGINS';
module.exports.SET_MARGIN_SINGLE_TOP = 'SET_MARGIN_SINGLE_TOP';
module.exports.SET_MARGIN_SINGLE_BOTTOM = 'SET_MARGIN_SINGLE_BOTTOM';
module.exports.SET_MARGIN_SINGLE_RIGHT = 'SET_MARGIN_SINGLE_RIGHT';
module.exports.SET_MARGIN_SINGLE_LEFT = 'SET_MARGIN_SINGLE_LEFT';
module.exports.SET_MARGIN_DOUBLE_TOP = 'SET_MARGIN_DOUBLE_TOP';
module.exports.SET_MARGIN_DOUBLE_BOTTOM = 'SET_MARGIN_DOUBLE_BOTTOM';
module.exports.SET_MARGIN_DOUBLE_RIGHT = 'SET_MARGIN_DOUBLE_RIGHT';
module.exports.SET_MARGIN_DOUBLE_LEFT = 'SET_MARGIN_DOUBLE_LEFT';

// TEXT
module.exports.API_TEXT = 'API_TEXT';
module.exports.SET_HEADLINE = 'SET_HEADLINE';
module.exports.SET_CHATTER = 'SET_CHATTER';
module.exports.SET_FOOTNOTE = 'SET_FOOTNOTE';
module.exports.SET_DATASOURCE = 'SET_DATASOURCE';
module.exports.SET_AUTHOR = 'SET_AUTHOR';

// SCRIPTS
module.exports.API_SCRIPTS = 'API_SCRIPTS';
module.exports.SET_DRAW_SCRIPT = 'SET_DRAW_SCRIPT';
module.exports.SET_HELPER_SCRIPT = 'SET_HELPER_SCRIPT';
module.exports.SET_STYLES = 'SET_STYLES';
module.exports.SET_HTML = 'SET_HTML';
