
// DATA COLUMN MAPPING
export const API_DATAMAP = 'API_DATAMAP';

export const ADD_BASE = 'ADD_BASE';
export const ADD_VALUE = 'ADD_VALUE';
export const ADD_SCALE = 'ADD_SCALE';
export const ADD_SERIES = 'ADD_SERIES';
export const ADD_FACET = 'ADD_FACET';
export const ADD_ANNOTATIONS = 'ADD_ANNOTATIONS';
export const ADD_IGNORE = 'ADD_IGNORE';

export const REMOVE_BASE = 'REMOVE_BASE';
export const REMOVE_VALUE = 'REMOVE_VALUE';
export const REMOVE_SCALE = 'REMOVE_SCALE';
export const REMOVE_SERIES = 'REMOVE_SERIES';
export const REMOVE_FACET = 'REMOVE_FACET';
export const REMOVE_ANNOTATIONS = 'REMOVE_ANNOTATIONS';
export const REMOVE_IGNORE = 'REMOVE_IGNORE';

export const SET_HEADER_SORT = 'SET_HEADER_SORT';

export const RESET_DATAMAP = 'RESET_DATAMAP';

// ATTACH DATA
export const API_DATA = 'API_DATA';
export const ATTACH_DATA = 'ATTACH_DATA';

// AXES
export const API_AXES = 'API_AXES';

// COLOR AXIS
export const SET_COLOR_SCHEME = 'SET_COLOR_SCHEME';
export const SET_COLOR = 'SET_COLOR';
export const UNSET_COLOR = 'UNSET_COLOR';
export const RESET_COLOR = 'RESET_COLOR';
export const COLOR_BY_FACET = 'COLOR_BY_FACET';
export const IGNORE_SCALE = 'IGNORE_SCALE';
export const SET_QUANTIZE = 'SET_QUANTIZE';
export const UNSET_QUANTIZE = 'UNSET_QUANTIZE';
export const SET_QUANTIZE_COLUMN = 'SET_QUANTIZE_COLUMN';
export const UNSET_QUANTIZE_COLUMN = 'UNSET_QUANTIZE_COLUMN';
export const SET_QUANTIZE_DOMAIN = 'SET_QUANTIZE_DOMAIN';
export const SET_QUANTIZE_RANGE = 'SET_QUANTIZE_RANGE';
export const SET_QUANTIZE_GROUPS = 'SET_QUANTIZE_GROUPS';
export const SET_QUANTIZE_REVERSE = 'SET_QUANTIZE_REVERSE';

// BASE AXIS
export const SET_BASE_TYPE = 'SET_BASE_TYPE';
export const SET_DATE_FORMAT = 'SET_DATE_FORMAT';
export const UNSET_DATE_FORMAT = 'UNSET_DATE_FORMAT';
export const SET_BASE_SINGLE_DATESTRING = 'SET_BASE_SINGLE_DATESTRING';
export const SET_BASE_SINGLE_FREQUENCY = 'SET_BASE_SINGLE_FREQUENCY';
export const SET_BASE_DOUBLE_DATESTRING = 'SET_BASE_DOUBLE_DATESTRING';
export const SET_BASE_DOUBLE_FREQUENCY = 'SET_BASE_DOUBLE_FREQUENCY';
export const SET_BASE_SINGLE_TICKS = 'SET_BASE_SINGLE_TICKS';
export const SET_BASE_SINGLE_CUSTOMTICKS = 'SET_BASE_SINGLE_CUSTOMTICKS';
export const SET_BASE_DOUBLE_TICKS = 'SET_BASE_DOUBLE_TICKS';
export const SET_BASE_DOUBLE_CUSTOMTICKS = 'SET_BASE_DOUBLE_CUSTOMTICKS';
export const SET_BASE_MIN = 'SET_BASE_MIN';
export const SET_BASE_MAX = 'SET_BASE_MAX';
export const SET_BASE_LABEL = 'SET_BASE_LABEL';
export const SET_BASE_SUFFIX = 'SET_BASE_SUFFIX';
export const SET_BASE_PREFIX = 'SET_BASE_PREFIX';
export const ADD_BASE_SHADED_REGION = 'ADD_BASE_SHADED_REGION';
export const SET_BASE_SHADED_REGION_MIN = 'SET_BASE_SHADED_REGION_MIN';
export const SET_BASE_SHADED_REGION_MAX = 'SET_BASE_SHADED_REGION_MAX';
export const REMOVE_BASE_SHADED_REGION = 'REMOVE_BASE_SHADED_REGION';


// VALUE AXIS
export const SET_VALUE_SINGLE_TICKS = 'SET_VALUE_SINGLE_TICKS';
export const SET_VALUE_SINGLE_CUSTOMTICKS = 'SET_VALUE_SINGLE_CUSTOMTICKS';
export const SET_VALUE_DOUBLE_TICKS = 'SET_VALUE_DOUBLEwerk._TICKS';
export const SET_VALUE_DOUBLE_CUSTOMTICKS = 'SET_VALUE_DOUBLE_CUSTOMTICKS';
export const SET_VALUE_MIN = 'SET_VALUE_MIN';
export const SET_VALUE_MAX = 'SET_VALUE_MAX';
export const SET_VALUE_LABEL = 'SET_VALUE_LABEL';
export const SET_VALUE_SUFFIX = 'SET_VALUE_SUFFIX';
export const SET_VALUE_PREFIX = 'SET_VALUE_PREFIX';
export const ADD_VALUE_SHADED_REGION = 'ADD_VALUE_SHADED_REGION';
export const SET_VALUE_SHADED_REGION_MIN = 'SET_VALUE_SHADED_REGION_MIN';
export const SET_VALUE_SHADED_REGION_MAX = 'SET_VALUE_SHADED_REGION_MAX';
export const REMOVE_VALUE_SHADED_REGION = 'REMOVE_VALUE_SHADED_REGION';

// SCALE AXIS
export const SET_SCALE_PREFIX = 'SET_SCALE_PREFIX';
export const SET_SCALE_SUFFIX = 'SET_SCALE_SUFFIX';


// MARGINS
export const API_MARGINS = 'API_MARGINS';
export const SET_MARGIN_SINGLE_TOP = 'SET_MARGIN_SINGLE_TOP';
export const SET_MARGIN_SINGLE_BOTTOM = 'SET_MARGIN_SINGLE_BOTTOM';
export const SET_MARGIN_SINGLE_RIGHT = 'SET_MARGIN_SINGLE_RIGHT';
export const SET_MARGIN_SINGLE_LEFT = 'SET_MARGIN_SINGLE_LEFT';
export const SET_MARGIN_DOUBLE_TOP = 'SET_MARGIN_DOUBLE_TOP';
export const SET_MARGIN_DOUBLE_BOTTOM = 'SET_MARGIN_DOUBLE_BOTTOM';
export const SET_MARGIN_DOUBLE_RIGHT = 'SET_MARGIN_DOUBLE_RIGHT';
export const SET_MARGIN_DOUBLE_LEFT = 'SET_MARGIN_DOUBLE_LEFT';

// TEXT
export const API_TEXT = 'API_TEXT';
export const SET_HEADLINE = 'SET_HEADLINE';
export const SET_CHATTER = 'SET_CHATTER';
export const SET_FOOTNOTE = 'SET_FOOTNOTE';
export const SET_DATASOURCE = 'SET_DATASOURCE';
export const SET_AUTHOR = 'SET_AUTHOR';
export const ADD_ANNOTATION = 'ADD_ANNOTATION';
export const REMOVE_ANNOTATION = 'REMOVE_ANNOTATION';
export const CHANGE_ANNOTATION = 'CHANGE_ANNOTATION';
export const CHANGE_ANNOTATION_TEXT = 'CHANGE_ANNOTATION_TEXT';
export const CHANGE_ANNOTATION_POSITION = 'CHANGE_ANNOTATION_POSITION';
export const CHANGE_ANNOTATION_DIMENSIONS = 'CHANGE_ANNOTATION_DIMENSIONS';
export const CHANGE_ANNOTATION_ALIGN = 'CHANGE_ANNOTATION_ALIGN';
export const CHANGE_ANNOTATION_FONT_SIZE = 'CHANGE_ANNOTATION_FONT_SIZE';
export const CHANGE_ANNOTATION_BACKGROUND = 'CHANGE_ANNOTATION_BACKGROUND';
export const CHANGE_ANNOTATION_SIZE = 'CHANGE_ANNOTATION_SIZE';
export const CHANGE_ANNOTATION_COLOR = 'CHANGE_ANNOTATION_COLOR';
export const SET_LEGEND_ACTIVE = 'SET_LEGEND_ACTIVE';
export const UNSET_LEGEND = 'UNSET_LEGEND';
export const SET_LEGEND_KEYS = 'SET_LEGEND_KEYS';
export const CHANGE_LEGEND_KEY = 'CHANGE_LEGEND_KEY';
export const CHANGE_LEGEND_KEY_ORDER_UP = 'CHANGE_LEGEND_KEY_ORDER_UP';
export const CHANGE_LEGEND_KEY_ORDER_DOWN = 'CHANGE_LEGEND_KEY_ORDER_DOWN';
export const CHANGE_LEGEND_TITLE = 'CHANGE_LEGEND_TITLE';
export const CHANGE_LEGEND_ALIGN = 'CHANGE_LEGEND_ALIGN';
export const CHANGE_LEGEND_BACKGROUND = 'CHANGE_LEGEND_BACKGROUND';
export const CHANGE_LEGEND_INSIDE = 'CHANGE_LEGEND_INSIDE';
export const CHANGE_LEGEND_POSITION = 'CHANGE_LEGEND_POSITION';
export const CHANGE_LEGEND_WIDTH = 'CHANGE_LEGEND_WIDTH';
export const SET_CHART_TITLE = 'SET_CHART_TITLE';

// SCRIPTS
export const API_SCRIPTS = 'API_SCRIPTS';
export const SET_DRAW_SCRIPT = 'SET_DRAW_SCRIPT';
export const SET_HELPER_SCRIPT = 'SET_HELPER_SCRIPT';
export const SET_STYLES = 'SET_STYLES';
export const SET_HTML = 'SET_HTML';
export const SET_DEPENDENCIES = 'SET_DEPENDENCIES';

// Template
export const API_TEMPLATE = 'API_TEMPLATE';
export const SET_TEMPLATE_TITLE = 'SET_TEMPLATE_TITLE';
export const SET_TEMPLATE_DESCRIPTION = 'SET_TEMPLATE_DESCRIPTION';
export const SET_TEMPLATE_ICON = 'SET_TEMPLATE_ICON';
export const ADD_TEMPLATE_TAG = 'ADD_TEMPLATE_TAG';
export const REMOVE_TEMPLATE_TAG = 'REMOVE_TEMPLATE_TAG';

// UI
export const API_UI = 'API_UI';
export const SET_RAW_DATA = 'SET_RAW_DATA';
export const CHANGE_PREVIEW = 'CHANGE_PREVIEW';

// EMBED
export const API_EMBED = 'API_EMBED';
export const SET_EMBED_DIMENSIONS = 'SET_EMBED_DIMENSIONS';
